config/routes.rb
Attachments::Application.routes.draw do
  resources :attachments
  
  root to: 'attachments#index'

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  attr_accessible :name, :document, :document_ipaper_id, :document_ipaper_access_key
  
  mount_uploader :document, DocumentUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  def index
    @attachments = Attachment.all
  end

  def show
    @attachment = Attachment.find(params[:id])
  end

  def new
    @attachment = Attachment.new
  end

  def create
    @attachment = Attachment.new(params[:attachment])
    if @attachment.save
      redirect_to @attachment, :notice => "Successfully created attachment."
    else
      render :action => 'new'
    end
  end

  def edit
    @attachment = Attachment.find(params[:id])
  end

  def update
    @attachment = Attachment.find(params[:id])
    if @attachment.update_attributes(params[:attachment])
      redirect_to @attachment, :notice  => "Successfully updated attachment."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @attachment = Attachment.find(params[:id])
    @attachment.destroy
    redirect_to attachments_url, :notice => "Successfully destroyed attachment."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/attachments/_form.html.erb
<%= form_for @attachment, html: {multipart: true} do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :document %><br />
    <%= f.file_field :document %>
    <%= f.hidden_field :document_cache %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/attachments/edit.html.erb
<% title "Edit Attachment" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @attachment %> |
  <%= link_to "View All", attachments_path %>
</p>

app/views/attachments/index.html.erb
<% title "Attachments" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for attachment in @attachments %>
    <tr>
      <td><%= attachment.name %></td>
      <td><%= link_to "Show", attachment %></td>
      <td><%= link_to "Edit", edit_attachment_path(attachment) %></td>
      <td><%= link_to "Destroy", attachment, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Attachment", new_attachment_path %></p>

app/views/attachments/new.html.erb
<% title "New Attachment" %>

<%= render 'form' %>

<p><%= link_to "Back to List", attachments_path %></p>

app/views/attachments/show.html.erb
<% title "Attachment" %>

<p>
  <strong>Name:</strong>
  <%= @attachment.name %>
</p>

<p>
  <%= link_to "(fullscreen)", @attachment.document.fullscreen_url %>
</p>

<p>
  <%== @attachment.document.display_ipaper unless @attachment.document.blank? %>
</p>

<p>
  <%= link_to "Edit", edit_attachment_path(@attachment) %> |
  <%= link_to "Destroy", @attachment, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", attachments_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>